#!/usr/bin/env python3
"""Generate the build-time C include for the RA80 RAM-only stage module."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


FNV1A_OFFSET = 0x811C9DC5
FNV1A_PRIME = 0x01000193
MIN_PAYLOAD = 64 * 1024
MAX_PAYLOAD = 2 * 1024 * 1024


def fnv1a(data: bytes) -> int:
    value = FNV1A_OFFSET
    for byte in data:
        value ^= byte
        value = (value * FNV1A_PRIME) & 0xFFFFFFFF
    return value


def u32le(data: bytes, offset: int) -> int:
    return int.from_bytes(data[offset : offset + 4], "little")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--source-commit", required=True)
    args = parser.parse_args()

    data = args.input.read_bytes()
    if not MIN_PAYLOAD <= len(data) <= MAX_PAYLOAD:
        raise SystemExit(f"unexpected U-Boot payload length: {len(data)}")

    vectors = [u32le(data, offset) for offset in range(0, 16, 4)]
    if vectors[0] & 0xFF000000 != 0xEA000000:
        raise SystemExit(f"unexpected first branch vector: 0x{vectors[0]:08x}")
    if vectors[1:] != [0xE59FF014, 0xE59FF014, 0xE59FF014]:
        raise SystemExit(
            "unexpected U-Boot literal vectors: "
            + " ".join(f"0x{word:08x}" for word in vectors)
        )

    sha256 = hashlib.sha256(data).hexdigest()
    checksum = fnv1a(data)
    lines = [
        "/* Generated by tools/ra80-kmod/bin2c.py; do not edit. */",
        "#ifndef RA80_PAYLOAD_INC",
        "#define RA80_PAYLOAD_INC",
        f"#define RA80_PAYLOAD_LEN {len(data)}U",
        f"#define RA80_PAYLOAD_FNV1A 0x{checksum:08x}U",
        f'#define RA80_PAYLOAD_SHA256 "{sha256}"',
        f'#define RA80_PAYLOAD_SOURCE_COMMIT "{args.source_commit}"',
        "static const u8 ra80_payload[RA80_PAYLOAD_LEN] __aligned(4) = {",
    ]

    for offset in range(0, len(data), 12):
        chunk = data[offset : offset + 12]
        lines.append("\t" + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")

    lines.extend(["};", "#endif", ""])
    args.output.write_text("\n".join(lines), encoding="ascii")

    print(f"payload_len={len(data)}")
    print(f"payload_fnv1a={checksum:08x}")
    print(f"payload_sha256={sha256}")
    print("payload_vectors=" + " ".join(f"{word:08x}" for word in vectors))


if __name__ == "__main__":
    main()
