#!/usr/bin/env python3
"""Generate the build-time C include for the RA80 RAM-only stage module."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


FNV1A_OFFSET = 0x811C9DC5
FNV1A_PRIME = 0x01000193
MIN_PAYLOAD = 64 * 1024
MAX_PAYLOAD = 0xE0000  # 0x4AA00000 reserved end - 0x4A920000 entry
RAMBOOT_BASE = 0x4A920000
RAMBOOT_MAGIC_GUARD = 0x5241382F
RAMBOOT_MAGIC_ARMED = 0x52413830


def fnv1a(data: bytes) -> int:
    value = FNV1A_OFFSET
    for byte in data:
        value ^= byte
        value = (value * FNV1A_PRIME) & 0xFFFFFFFF
    return value


def u32le(data: bytes, offset: int) -> int:
    return int.from_bytes(data[offset : offset + 4], "little")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--source-commit", required=True)
    parser.add_argument("--ramboot-magic-address", type=lambda value: int(value, 0))
    args = parser.parse_args()

    data = args.input.read_bytes()
    if not MIN_PAYLOAD <= len(data) <= MAX_PAYLOAD:
        raise SystemExit(f"unexpected U-Boot payload length: {len(data)}")

    vectors = [u32le(data, offset) for offset in range(0, 16, 4)]
    if vectors[0] & 0xFF000000 != 0xEA000000:
        raise SystemExit(f"unexpected first branch vector: 0x{vectors[0]:08x}")
    if vectors[1:] != [0xE59FF014, 0xE59FF014, 0xE59FF014]:
        raise SystemExit(
            "unexpected U-Boot literal vectors: "
            + " ".join(f"0x{word:08x}" for word in vectors)
        )

    sha256 = hashlib.sha256(data).hexdigest()
    checksum = fnv1a(data)
    magic_offset = None
    if args.ramboot_magic_address is not None:
        magic_offset = args.ramboot_magic_address - RAMBOOT_BASE
        if magic_offset < 0 or magic_offset + 4 > len(data) or magic_offset % 4:
            raise SystemExit(
                f"RAM-boot marker address is outside/alignment-invalid: "
                f"0x{args.ramboot_magic_address:08x}"
            )
        marker = u32le(data, magic_offset)
        if marker != RAMBOOT_MAGIC_GUARD:
            raise SystemExit(
                f"unexpected RAM-boot marker at offset 0x{magic_offset:x}: "
                f"0x{marker:08x}"
            )

    lines = [
        "/* Generated by tools/ra80-kmod/bin2c.py; do not edit. */",
        "#ifndef RA80_PAYLOAD_INC",
        "#define RA80_PAYLOAD_INC",
        f"#define RA80_PAYLOAD_LEN {len(data)}U",
        f"#define RA80_PAYLOAD_FNV1A 0x{checksum:08x}U",
        f'#define RA80_PAYLOAD_SHA256 "{sha256}"',
        f'#define RA80_PAYLOAD_SOURCE_COMMIT "{args.source_commit}"',
    ]

    if magic_offset is not None:
        lines.extend(
            [
                f"#define RA80_RAMBOOT_MAGIC_OFFSET 0x{magic_offset:x}U",
                f"#define RA80_RAMBOOT_MAGIC_GUARD 0x{RAMBOOT_MAGIC_GUARD:08x}U",
                f"#define RA80_RAMBOOT_MAGIC_ARMED 0x{RAMBOOT_MAGIC_ARMED:08x}U",
            ]
        )

    lines.append("static const u8 ra80_payload[RA80_PAYLOAD_LEN] __aligned(4) = {")

    for offset in range(0, len(data), 12):
        chunk = data[offset : offset + 12]
        lines.append("\t" + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")

    lines.extend(["};", "#endif", ""])
    args.output.write_text("\n".join(lines), encoding="ascii")

    print(f"payload_len={len(data)}")
    print(f"payload_fnv1a={checksum:08x}")
    print(f"payload_sha256={sha256}")
    print("payload_vectors=" + " ".join(f"{word:08x}" for word in vectors))
    if magic_offset is not None:
        print(f"ramboot_magic_address={args.ramboot_magic_address:08x}")
        print(f"ramboot_magic_offset={magic_offset:x}")
        print(f"ramboot_magic_guard={RAMBOOT_MAGIC_GUARD:08x}")
        print(f"ramboot_magic_armed={RAMBOOT_MAGIC_ARMED:08x}")


if __name__ == "__main__":
    main()
